DebugMode: false
Positions:
  test:
    enable: true
    Start:
      World: world
      X: 0.0
      Y: 0.0
      Z: 0.0
    End:
      World: world
      X: 0.0
      Y: 0.0
      Z: 0.0
ExceptPlayers:
 - player_uuid: player_name